
development:
  adapter: postgresql
  encoding: unicode
  database: tps_development
  host: localhost
  pool: 5
  username: tps
  password: lol


test:
  adapter: postgresql
  encoding: unicode
  database: tps_test
  host: localhost
  pool: 5
  username: tps
  password: lol


