fr:
  links:
    provider:
      logo:
        src: "footer/logo-dmra-horisontal.png"
        alt: "Logo DMRA"
        height: 90
        width: 240
      name: "DMRA"
      provided_by: "la DMRA"
      title: "Direction de la Modernisation et des Réformes de l'Administration"
      url: "https://www.service-public.pf/voir/annuaire/dmra-direction-modernisation-et-reformes-administration/"
    footer:
      description_1: |
        Mes-Démarches est porté par la Direction de la Modernisation et des Réformes de l'Administration
        et est basé sur démarches-simplifiées.fr créé par
      aide:
        url: "https://faq.demarches-simplifiees.fr"
      cgu:
        url: "https://mes-demarches.gitbook.io/documentation/cgu"
      rgpd:
        label: "Données personnelles"
        title: "Données personnelles"
        url: "https://mes-demarches.gitbook.io/documentation/cgu#rgpd"
      doc:
        url: "https://mes-demarches.gitbook.io/documentation"
      faq:
        url: "https://mes-demarches.gitbook.io/documentation/questions-frequentes"
      mentions_legales:
        url: "https://mes-demarches.gitbook.io/documentation/cgu#mentions-legales"
      releases:
        url: "https://github.com/govpf/mes-demarches/releases"
      status_page:
        url: "https://updown.io/cugq"
